//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ByeWeek
    {
        public ByeWeek()
        {
            this.TeamByeWeeks = new HashSet<TeamByeWeek>();
        }
    
        public int Id { get; set; }
        public short WeekNumber { get; set; }
    
        public virtual ICollection<TeamByeWeek> TeamByeWeeks { get; set; }
    }
}
