//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FantasyTeam
    {
        public FantasyTeam()
        {
            this.DraftPicks = new HashSet<DraftPick>();
            this.LeagueYearDraftOrders = new HashSet<LeagueYearDraftOrder>();
            this.Tradees = new HashSet<Trade>();
            this.Traders = new HashSet<Trade>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OwnerName { get; set; }
    
        public virtual ICollection<DraftPick> DraftPicks { get; set; }
        public virtual ICollection<LeagueYearDraftOrder> LeagueYearDraftOrders { get; set; }
        public virtual ICollection<Trade> Tradees { get; set; }
        public virtual ICollection<Trade> Traders { get; set; }
    }
}
