//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyVBDEntities : DbContext
    {
        public FantasyVBDEntities()
            : base("name=FantasyVBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ByeWeek> ByeWeeks { get; set; }
        public DbSet<DraftPick> DraftPicks { get; set; }
        public DbSet<FantasyTeam> FantasyTeams { get; set; }
        public DbSet<League> Leagues { get; set; }
        public DbSet<LeagueYear> LeagueYears { get; set; }
        public DbSet<LeagueYearDraftOrder> LeagueYearDraftOrders { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Trade> Trades { get; set; }
        public DbSet<PlayerProjection> PlayerProjections { get; set; }
        public DbSet<LeagueYearPosition> LeagueYearPositions { get; set; }
        public DbSet<TeamByeWeek> TeamByeWeeks { get; set; }
    }
}
