//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueYear
    {
        public LeagueYear()
        {
            this.DraftPicks = new HashSet<DraftPick>();
            this.LeagueYearDraftOrders = new HashSet<LeagueYearDraftOrder>();
            this.Trades = new HashSet<Trade>();
            this.PlayerProjections = new HashSet<PlayerProjection>();
            this.LeagueYearPositions = new HashSet<LeagueYearPosition>();
            this.TeamByeWeeks = new HashSet<TeamByeWeek>();
        }
    
        public int Id { get; set; }
        public int LeagueId { get; set; }
        public string Season { get; set; }
    
        public virtual ICollection<DraftPick> DraftPicks { get; set; }
        public virtual League League { get; set; }
        public virtual ICollection<LeagueYearDraftOrder> LeagueYearDraftOrders { get; set; }
        public virtual ICollection<Trade> Trades { get; set; }
        public virtual ICollection<PlayerProjection> PlayerProjections { get; set; }
        public virtual ICollection<LeagueYearPosition> LeagueYearPositions { get; set; }
        public virtual ICollection<TeamByeWeek> TeamByeWeeks { get; set; }
    }
}
