//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerProjection
    {
        public int Id { get; set; }
        public int LeagueYearId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<decimal> Attempts { get; set; }
        public Nullable<decimal> Completions { get; set; }
        public Nullable<decimal> PassingYards { get; set; }
        public Nullable<decimal> PassingTDs { get; set; }
        public Nullable<decimal> Interceptions { get; set; }
        public Nullable<decimal> PasserRating { get; set; }
        public Nullable<decimal> RushAttempts { get; set; }
        public Nullable<decimal> RushYards { get; set; }
        public Nullable<decimal> RushAvg { get; set; }
        public Nullable<decimal> RushingTDs { get; set; }
        public Nullable<decimal> Targets { get; set; }
        public Nullable<decimal> Receptions { get; set; }
        public Nullable<decimal> ReceivingYards { get; set; }
        public Nullable<decimal> ReceivingAvg { get; set; }
        public Nullable<decimal> ReceivingTDs { get; set; }
        public Nullable<decimal> FumblesLost { get; set; }
        public Nullable<decimal> FantasyPoints { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<decimal> ValuePoints { get; set; }
        public Nullable<decimal> PassingAvg { get; set; }
        public Nullable<decimal> ValueDeltaPoints { get; set; }
        public Nullable<decimal> YardageBonusPoints { get; set; }
    
        public virtual LeagueYear LeagueYear { get; set; }
        public virtual Player Player { get; set; }
    }
}
