//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftAssistant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.DraftPicks = new HashSet<DraftPick>();
            this.PlayerProjections = new HashSet<PlayerProjection>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DraftAssistant.DataAccess.Enums.PositionType PositionType { get; set; }
        public int TeamId { get; set; }
    
        public virtual ICollection<DraftPick> DraftPicks { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<PlayerProjection> PlayerProjections { get; set; }
    }
}
